"""Rebuild HUB Mục lục pages — auto-list children theo hub_rules.

V4.1 logic:
- HUB-{master_hub_number} (default "001") = Master entry sticky (KHÔNG đổi mã)
- HUB-002, 003, ... = nhánh, chỉ tạo khi >= branch_hub_min_pages
- 4 branch patterns: A (sub-area), B (audience), C (lifecycle), D (role)

Usage:
    python3 scripts/rebuild_hub_toc.py                          # dry-run all sections
    python3 scripts/rebuild_hub_toc.py --section OPS-CS         # 1 section
    python3 scripts/rebuild_hub_toc.py --section OPS-CS --confirm  # push lên Lark
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

from _common import load_config, require_lark_auth, require_lark_cli


def list_children(parent_node_token: str) -> list[dict[str, Any]]:
    """List children pages of a Wiki node via lark-cli."""
    try:
        result = subprocess.run(
            ["lark-cli", "wiki", "node", "list",
             "--parent-node-token", parent_node_token, "--output", "json"],
            capture_output=True, text=True, check=True, timeout=30,
        )
        return json.loads(result.stdout)
    except (subprocess.CalledProcessError, json.JSONDecodeError) as e:
        print(f"❌ list_children failed for {parent_node_token}: {e}", file=sys.stderr)
        return []


def group_pages_by_type(pages: list[dict[str, Any]]) -> dict[str, list[dict]]:
    """Group pages by TYPE (3rd component of page code SPACE-SECTION-TYPE-NUMBER)."""
    groups: dict[str, list[dict]] = defaultdict(list)
    for p in pages:
        code = p.get("page_code", "")
        parts = code.split("-")
        if len(parts) >= 4:
            type_code = parts[-2]
            groups[type_code].append(p)
    return groups


def render_hub_content(
    section_code: str,
    section_name: str,
    pages: list[dict[str, Any]],
    cfg: dict[str, Any],
) -> str:
    """Render HUB-001 master content listing all pages by type."""
    hub_num = cfg["hub_rules"]["master_hub_number"]
    hub_code = f"{section_code}-HUB-{hub_num}"

    lines = [
        f"# {hub_code} {section_name} — Tổng quan",
        "",
        f"Hub Master cho section `{section_code}`. Sticky, không đổi mã.",
        "",
        f"Auto-generated by `scripts/rebuild_hub_toc.py`. Tổng {len(pages)} pages.",
        "",
    ]

    groups = group_pages_by_type(pages)

    # Order theo execution-first: HUB, MST, PROC, SOP, CHK, TMP, PBK, DBD, then others
    type_order = ["MST", "PROC", "SOP", "CHK", "TMP", "PBK", "DBD", "POL", "DIC", "GDL", "LOG", "IDX"]

    for t in type_order:
        if not groups.get(t):
            continue
        lines.append(f"\n### {t}")
        lines.append("")
        for p in sorted(groups[t], key=lambda x: x.get("page_code", "")):
            code = p.get("page_code", "?")
            name = p.get("page_name", "?")
            lines.append(f"- [[{code}]] {name}")

    # Cross-section link
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"→ ↑ [{cfg['company']['short_name']} Master Wiki Index]({cfg['lark']['wiki_root_url']})")

    return "\n".join(lines) + "\n"


def evaluate_branch_eligibility(pages: list[dict[str, Any]], cfg: dict[str, Any]) -> dict[str, bool]:
    """Check if HUB nhánh nên được tạo dựa vào branch_hub_min_pages.

    Return dict mapping pattern_name → eligible (True/False).
    Pattern detection trên thực tế cần manual judgment — chỉ check số lượng.
    """
    min_pages = cfg["hub_rules"]["branch_hub_min_pages"]
    return {
        "needs_branch_hub": len(pages) >= 2 * min_pages,
        "current_page_count": len(pages),
        "min_threshold": min_pages,
    }


def push_hub_to_lark(content: str, hub_obj_token: str) -> bool:
    """Push HUB content to Lark Docs."""
    tmp = Path("/tmp/hub-content.md")
    tmp.write_text(content)
    try:
        subprocess.run(
            ["lark-cli", "docs", "update", hub_obj_token,
             "--content", str(tmp), "--api-version", "v2"],
            check=True, timeout=60,
        )
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Push failed: {e}", file=sys.stderr)
        return False


def find_section_info(cfg: dict[str, Any], section_code: str) -> dict[str, str] | None:
    """Find section dict in config taxonomy."""
    for space_code, sections in cfg["taxonomy"]["sections"].items():
        for sec in sections:
            if sec["code"] == section_code:
                return {**sec, "space": space_code}
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Rebuild HUB Mục lục pages")
    parser.add_argument("--section", help="1 section code (vd OPS-CS). Default: all.")
    parser.add_argument("--confirm", action="store_true", help="Push lên Lark")
    parser.add_argument("--hub-obj-token", help="Obj token của HUB page (cần --confirm)")
    args = parser.parse_args()

    require_lark_cli()
    cfg = load_config()

    sections_to_rebuild: list[str] = []
    if args.section:
        sections_to_rebuild = [args.section]
    else:
        for space_code, secs in cfg["taxonomy"]["sections"].items():
            sections_to_rebuild.extend(s["code"] for s in secs)

    if args.confirm:
        require_lark_auth()

    for section_code in sections_to_rebuild:
        info = find_section_info(cfg, section_code)
        if not info:
            print(f"⚠️  Section {section_code} không có trong taxonomy.sections, skip.", file=sys.stderr)
            continue

        print(f"\n📑 Section {section_code} — {info['name']}")
        # Fetch children from Lark (skipped in dry-run if no auth)
        # In real usage, parent_node_token is the HUB-001's node_token. For demo:
        pages: list[dict[str, Any]] = []  # Would call list_children() if auth set up

        content = render_hub_content(section_code, info["name"], pages, cfg)
        eligibility = evaluate_branch_eligibility(pages, cfg)

        out = Path("dist") / f"hub-{section_code}-preview.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content)
        print(f"   ✓ Preview → {out}")
        print(f"   Branch eligibility: {eligibility}")

        if args.confirm and args.hub_obj_token:
            push_hub_to_lark(content, args.hub_obj_token)

    return 0


if __name__ == "__main__":
    sys.exit(main())
