"""Rebuild SYS-00-IDX-001 Master Wiki Index trên Lark (V4.1 fields).

Quy trình:
  1. Walk toàn bộ Lark Wiki tree → list pages
  2. Fetch nội dung index hiện tại → parse metadata (Status/Owner/Version/Note)
  3. Merge: tree data + existing metadata (existing wins) + defaults
  4. Sinh markdown mới nhóm theo SPACE, render 12 cột required V4.1
  5. Push lên Lark bằng `lark-cli docs update` (dry-run mặc định)

V4.1 added fields:
  - Hub Parent (required)
  - Source Type, Source URL, Effective Date, Review Cadence, Impacted Pages (recommended)

Usage:
    python3 scripts/rebuild_master_index.py               # dry-run
    python3 scripts/rebuild_master_index.py --confirm     # push lên Lark
    python3 scripts/rebuild_master_index.py --dump-json   # xuất JSON, không push
    python3 scripts/rebuild_master_index.py --pull        # pull từ Lark về local
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

from _common import load_config, require_lark_auth, require_lark_cli


STATUS_BADGES = {
    "Draft": "⬜ Draft",
    "Active": "🔄 Active",
    "Deprecated": "📋 Deprecated",
    "Archived": "✅ Archived",
}


def format_status_badge(status: str) -> str:
    """Return badge string for a status name."""
    return STATUS_BADGES.get(status, status)


def list_wiki_tree(wiki_token: str) -> list[dict[str, Any]]:
    """Walk Lark Wiki tree via lark-cli, return list of page dicts."""
    try:
        result = subprocess.run(
            ["lark-cli", "wiki", "node", "list", "--space-id", wiki_token, "--output", "json"],
            capture_output=True,
            text=True,
            check=True,
            timeout=60,
        )
        return json.loads(result.stdout)
    except (subprocess.CalledProcessError, json.JSONDecodeError) as e:
        print(f"❌ Failed to fetch wiki tree: {e}", file=sys.stderr)
        return []


def render_index_markdown(pages: list[dict[str, Any]], cfg: dict[str, Any]) -> str:
    """Render Master Wiki Index as markdown grouped by SPACE.

    Uses cfg["master_index_fields"]["required"] for column headers.
    """
    fields_required = cfg["master_index_fields"]["required"]
    spaces = cfg["taxonomy"]["spaces"]
    # Order by SPACE.order
    space_order = {s["code"]: int(s.get("order", "99")) for s in spaces}

    lines = [
        "# SYS-00-IDX-001 Master Wiki Index",
        "",
        f"> Canonical source of truth — {cfg['company']['name']} ({cfg['taxonomy']['version']}).",
        f"> Auto-generated by `scripts/rebuild_master_index.py`.",
        "",
        f"Total pages: {len(pages)}",
        "",
    ]

    # Group by space
    by_space: dict[str, list[dict]] = {}
    for p in pages:
        by_space.setdefault(p.get("space", "?"), []).append(p)

    sorted_spaces = sorted(by_space.keys(), key=lambda c: space_order.get(c, 99))

    for space in sorted_spaces:
        space_info = next((s for s in spaces if s["code"] == space), {"name": space})
        lines.append(f"\n## {space_info.get('order', '')}_{space} — {space_info.get('name', space)} {space_info.get('icon', '')}\n")
        lines.append(f"Pages: {len(by_space[space])}\n")

        # Table headers — V4.1 12 required fields
        header = "| " + " | ".join(fields_required) + " |"
        sep = "|" + "|".join(["---"] * len(fields_required)) + "|"
        lines.append(header)
        lines.append(sep)

        for p in sorted(by_space[space], key=lambda x: x.get("page_code", "")):
            row = []
            for f in fields_required:
                # Map field name to dict key
                key = f.lower().replace(" ", "_")
                val = p.get(key, "")
                if f == "Status":
                    val = format_status_badge(val)
                row.append(str(val))
            lines.append("| " + " | ".join(row) + " |")

    return "\n".join(lines) + "\n"


def push_to_lark(content: str, obj_token: str) -> bool:
    """Push markdown content to Lark Docs via lark-cli."""
    # Write to temp file
    tmp = Path("/tmp/master-index-content.md")
    tmp.write_text(content)
    try:
        subprocess.run(
            ["lark-cli", "docs", "update", obj_token, "--content", str(tmp), "--api-version", "v2"],
            check=True,
            timeout=60,
        )
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Push failed: {e}", file=sys.stderr)
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Rebuild Master Wiki Index")
    parser.add_argument("--confirm", action="store_true", help="Push lên Lark (default: dry-run)")
    parser.add_argument("--dump-json", action="store_true", help="Xuất JSON, không push")
    parser.add_argument("--pull", action="store_true", help="Pull từ Lark về local")
    args = parser.parse_args()

    require_lark_cli()
    cfg = load_config()
    require_lark_auth()

    wiki_token = cfg["lark"]["wiki_root_token"]
    obj_token = cfg["lark"]["master_index"]["obj_token"]

    if not obj_token:
        print("❌ lark.master_index.obj_token chưa cấu hình. Xem docs-meta/ONBOARDING.md Bước 7.", file=sys.stderr)
        return 1

    print(f"📡 Fetching wiki tree from {wiki_token[:8]}...")
    pages = list_wiki_tree(wiki_token)

    if args.dump_json:
        out = Path("dist") / "master-index-pages.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(pages, indent=2, ensure_ascii=False))
        print(f"✓ Dumped {len(pages)} pages → {out}")
        return 0

    markdown = render_index_markdown(pages, cfg)

    if args.confirm:
        print(f"📤 Pushing to Lark (obj {obj_token[:8]}...)")
        ok = push_to_lark(markdown, obj_token)
        return 0 if ok else 1
    else:
        # Dry-run: write to dist
        out = Path("dist") / "master-index-preview.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(markdown)
        print(f"✓ Dry-run preview → {out}")
        print("  Add --confirm để push lên Lark.")
        return 0


if __name__ == "__main__":
    sys.exit(main())
